export const LOAD_PROMOTIONS_REQUEST = 'LOAD_PROMOTIONS_REQUEST'
export const LOAD_PROMOTIONS_SUCCESS = 'LOAD_PROMOTIONS_SUCCESS'
export const LOAD_PROMOTIONS_FAILURE = 'LOAD_PROMOTIONS_FAILURE'

export const DELETE_PROMOTION_REQUEST = 'DELETE_PROMOTION_REQUEST'
export const DELETE_PROMOTION_SUCCESS = 'DELETE_PROMOTION_SUCCESS'
export const DELETE_PROMOTION_FAILURE = 'DELETE_PROMOTION_FAILURE'