export const LOAD_PROMOTIONS_REQUEST = 'LOAD_PROMOTIONS_REQUEST';
export const LOAD_PROMOTIONS_SUCCESS = 'LOAD_PROMOTIONS_SUCCESS';
export const LOAD_PROMOTIONS_FAILURE = 'LOAD_PROMOTIONS_FAILURE';

export const LOAD_PROMOTION_REQUEST = 'LOAD_PROMOTION_REQUEST';
export const LOAD_PROMOTION_SUCCESS = 'LOAD_PROMOTION_SUCCESS';
export const LOAD_PROMOTION_FAILURE = 'LOAD_PROMOTION_FAILURE';

export const CREATE_PROMOTION_REQUEST = 'CREATE_PROMOTION_REQUEST';
export const CREATE_PROMOTION_SUCCESS = 'CREATE_PROMOTION_SUCCESS';
export const CREATE_PROMOTION_FAILURE = 'CREATE_PROMOTION_FAILURE';

export const UPDATE_PROMOTION_REQUEST = 'UPDATE_PROMOTION_REQUEST';
export const UPDATE_PROMOTION_SUCCESS = 'UPDATE_PROMOTION_SUCCESS';
export const UPDATE_PROMOTION_FAILURE = 'UPDATE_PROMOTION_FAILURE';

export const DELETE_PROMOTION_REQUEST = 'DELETE_PROMOTION_REQUEST';
export const DELETE_PROMOTION_SUCCESS = 'DELETE_PROMOTION_SUCCESS';
export const DELETE_PROMOTION_FAILURE = 'DELETE_PROMOTION_FAILURE';